config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :jobs
  resources :feedbacks
  resource :dashboard

  root 'homes#show'
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user

  

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  
  geocoded_by :address
  after_validation :geocode
  
  validate :title
  validate :description
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :feedbacks

  validate :first_name
  validate :last_name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_user!

  def show
    distance = params[:distance].blank? ? 10 : params[:distance].to_i 
    @jobs = Job.where.not(user: current_user)
    @jobs = @jobs.near(params[:location], distance) if params[:location].present?
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]


  def new
    @feedback = Feedback.new
  end

  def create
    @user = User.find_by(email: params[:distant_email])
    if @user
      @user.update_attribute(:time, @user.time + feedback_params[:time].to_i)
      current_user.update_attribute(:time, current_user.time - feedback_params[:time].to_i)

      @feedback = @user.feedbacks.new(feedback_params)
      if @feedback.save
        redirect_to :jobs, notice: 'feedback was successfully created.'
      else
        render :new
      end
    else
      render :new
    end
  end

  def update
    if @feedback.update(@feedback_params)
      redirect_to @feedback, notice: 'feedback was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @feedback.destroy
    redirect_to feedbacks_url, notice: 'feedback was successfully destroyed.'
  end

  private

  def set_feedback
    @feedback = feedback.find(params[:id])
  end

  def feedback_params
    params.require(:feedback).permit(:note, :comment, :time)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = current_user.jobs
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_user.jobs.new(job_params)
    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  def update
    if @job.update(job_params)
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    job_params = params.require(:job).permit(:title, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/dashboard/index.slim
h2= t('welcome_on_board')

= form_tag(dashboard_search_path, method: 'get') do
  = label_tag(:location, t('where') + ' ')
  = text_field_tag(:location)
  = label_tag(:distance, t('distance') + ' ')
  = text_field_tag(:distance)
  = 'km'
  = submit_tag(t('search'))

table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th= t('job')
      th= t('description')
      th= t('location')
  - @jobs.each do |job|
    tbody
      tr
        td= link_to job.title, job_url(job)
        td= job.description
        td= job.address

app/views/dashboards/show.slim
h2= t('welcome_on_board')

= form_tag(:dashboard, method: 'get') do
  = label_tag(:location, t('where') + ' ')
  = text_field_tag(:location)
  = label_tag(:distance, t('distance') + ' ')
  = text_field_tag(:distance)
  | km
  = submit_tag(t('search'))

table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th= t('job')
      th= t('description')
      th= t('location')
  - @jobs.each do |job|
    tbody
      tr
        td= link_to job.title, job_url(job)
        td= job.description
        td= job.address

app/views/feedbacks/_form.slim
- if @feedback.errors.any?
  div id='error_explanation'
    h2= pluralize(@feedback.errors.count, "error") + "prohibited this feedback from being saved:"
    ul
      - @feedback.errors.full_messages.each do |message|
      li= message

= simple_form_for(@feedback) do |f|
  = f.input :time, wrapper: :vertical_input_group

  = f.input :note, wrapper: :vertical_input_group
  = f.input :comment, wrapper: :vertical_input_group
  = label_tag 'distant_email', 'Email de l\'utilisateur'
  br
  = text_field_tag :distant_email, '', id: 'distant_email'
  br
  = f.button :submit
br

app/views/feedbacks/new.slim
h1= 'New feedback'

= render 'form'

= link_to 'Back', :back

app/views/homes/show.slim
h1 Welcome on E-Change

- if current_user.nil?
  = link_to t('welcome_new_user'), new_user_registration_path
- else
  .span1
    - unless current_user.time.blank?
      = "Il vous reste #{current_user.time/60} heures et #{current_user.time%60} minutes à dépenser"
      br
      - if current_user.time > 0

        = link_to 'Vous cherchez quelqu\'un', dashboard_path
  br
  .span1
    = link_to 'Vous proposez du travail', jobs_path

app/views/jobs/_form.slim
- if @job.errors.any?
  div id='error_explanation'
    h2= pluralize(@job.errors.count, "error") + "prohibited this job from being saved:"
    ul
      - @job.errors.full_messages.each do |message|
      li= message

= simple_form_for(@job) do |f|
  = f.input :title, wrapper: :vertical_input_group
  = f.input :description, wrapper: :vertical_input_group
  = f.input :address, wrapper: :vertical_input_group
  = f.button :submit
br

app/views/jobs/edit.slim
h1= 'Editing job'

= render 'form'

= link_to 'Show', @job
= '|'
= link_to 'Back', jobs_path

app/views/jobs/index.slim
h1= 'Your jobs'

table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th= 'Job name'
      th= 'Details'
      th= 'Edit'
      th= 'Not my job anymore'

  tbody
    - @jobs.each do |job|
      tr
        td= job.title
        td= link_to(job.description[0, 30] + '...', job) if job.description
        td= link_to 'Edit', edit_job_path(job)
        td= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }
br

= link_to 'New Job', new_job_path
br
= link_to 'Back', root_path

app/views/jobs/new.slim
h1= 'New job'

= render 'form'

= link_to 'Back', jobs_path

app/views/jobs/show.slim
p id='notice'
  = notice

.container.container-fluid  
  h2= @job.title
  strong
  
    = @job.description
    br
    br
    = @job.address
  br
  br

- if @job.user == current_user
  = link_to 'Give time and feedback', new_feedback_path
  br
  = link_to 'Edit', edit_job_path(@job)
- else
  = link_to @job.user.email, "mailto:#{@job.user.email}?subject=#{@job.title}&body=I'm interested by your job"

br
= link_to 'Back', jobs_path

app/views/layouts/application.slim
doctype html
html
  head
    title= 'EChange'
    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true)
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    p.navbar-text.pull-right
      - if user_signed_in?
        = t('logged_in_as')
        = ' '
        strong= current_user.email
        = ' '
        = link_to t('edit_profile'), edit_user_registration_path, class: 'navbar-link'
        = ' | '
        = link_to t('log_out'), destroy_user_session_path, method: :delete, class: 'navbar-link'
      - else
        = link_to t('sign_up'), new_user_registration_path, class: 'navbar-link'
        = ' | '
        = link_to t('log_in'), new_user_session_path, class: 'navbar-link'
  
    - if notice
      p.alert.alert-success
        = notice
    - if alert
      p.alert.alert-danger
        = alert
    div.container-fluid
      == yield
  